more fixes

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -66,11 +66,12 @@ jobs:
           PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}
         with:
           script: |
-            const output = `| Terraform Format and Style 🖌 | \`${{ steps.fmt.outcome }}\` |
-            | ---------------------------- | -------------------------------- |
-            | Terraform Initialization ⚙️ | \`${{ steps.init.outcome }}\` |
-            | Terraform Validation 🤖 | \`${{ steps.validate.outcome }}\` |
-            | Terraform Plan 📖 | \`${{ steps.plan.outcome }}\` |
+            const output = `
+            | Terraform Format and Style | \`${{ steps.fmt.outcome }}\`      |
+            | -------------------------- | --------------------------------- |
+            | Terraform Initialization   | \`${{ steps.init.outcome }}\`     |
+            | Terraform Validation       | \`${{ steps.validate.outcome }}\` |
+            | Terraform Plan             | \`${{ steps.plan.outcome }}\`     |
   
             <details><summary>Show Plan</summary>
   
@@ -79,7 +80,7 @@ jobs:
             \`\`\`
   
             </details>
-            *Pushed by: @${{ github.actor }}*`;
+            **Pushed by: @${{ github.actor }}**`;
   
             github.rest.issues.createComment({
               issue_number: context.issue.number,
@@ -88,9 +89,14 @@ jobs:
               body: output
             })
       
+      # Fail the workflow if the plan step failed
       - name: Terraform Plan Status
         if: github.event_name == 'pull_request'
-        run: exit ${{ steps.plan.outcome == 'success' && 0 || 1 }}
+        run: |
+          if [ "${{ steps.plan.outcome }}" != "success" ]; then
+            echo "Terraform plan failed. Failing the workflow."
+            exit 1
+          fi
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
